version: '3'

services:
  # strapi:
  #   container_name: strapi
  #   image: strapi/strapi
  #   platform: linux/amd64
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=1337
  #     - NODE_ENV=production
  #     - DATABASE_CLIENT=postgres
  #     - DATABASE_HOST=db
  #     - DATABASE_PORT=5432
  #     - DATABASE_NAME=strapi
  #     - DATABASE_USERNAME=strapi
  #     - DATABASE_PASSWORD=strapi
  #     - PUBLIC_URL=http://54.169.67.146:1337
  #     - API_TOKEN_SALT=token_salt
  #     - ADMIN_JWT_SECRET=admin_jwt_secret
  #     - TRANSFER_TOKEN_SALT=transfer_token_salt
  #   ports:
  #     - 1337:1337
  #   volumes:
  #     - ./app:/srv/app
  #   depends_on:
  #     - db
  #   command: 'strapi start'

  db:
    container_name: postgres
    image: postgres
    platform: linux/amd64
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi